name: Moje testy

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        
        steps:
            - uses: actions/checkout@v3
            
            - name: Nastav Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Nainstaluj zavislosti
              run: |
                  python -m pip install pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt

            - name: Otestuj kod pytestem
              run: pytest -v

            - name: Otestuj pokryti
              run: pytest -cov
